### PR TITLE
Navigate to correct mode when leaving settings

### LINKED ISSUE #244: Nach "Settings" wechselt es immer in den Viewer Mode
**Repro Steps:**

1. BDMS > Editor Modus
2. Settings öffnen
3. Zurück mit "Done"

**Erwartet:**
Die Applikation befindet sich immer noch im Editor Mode

**Beobachtet:**
Die Applikation befindet sich im Viewer Mode

### PR DESCRIPTION
**Pull request by danjov**
Fixes #244

### CODE REVIEW

File: src/client/cypress/e2e/testHelpers.js [hunk 1]
```diff
@@ -149,15 +149,21 @@ export const loginAndResetState = () => {
...
+        resetOccurred = true;
+        deleteBorehole(borehole.id); // max id in seed data.
+      }
     });
   });
 
-  cy.contains("a", "Refresh").click();
-  cy.wait("@edit_list");
-  cy.get("tbody").children().should("have.length", 100); // number or boreholes visible in editor mode (with paging).
+  if (resetOccurred) {
```
Comment (MiraGeowerkstatt) [inline src/client/cypress/e2e/testHelpers.js:162]: <3

**Review by MiraGeowerkstatt — APPROVED** [review]
